spring:
    profiles:
        active: prod
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3308/foo?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 1q2w3e4r1!

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                default_batch_fetch_size: 1000
            open-in-view: false

logging:
    level:
        org.hibernate.SQL: info
        root: info

server:
    port: 80